---
title: "Seurat_Practice_Mouse_Liver"
author: "Nicholas Carey"
date: "9/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
dir_prefix <- "/krummellab/data1/nicholascarey/mouse_liver/merged_E1_liver_singlets/"
```

## Hackathon 2021

This document is to practice working with Seurat.

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
library(Seurat)
library(dplyr)
library(dittoSeq)
library(ggplot2) 
library(ggrepel)
library(DESeq2)
library(patchwork)
library(harmony)
```

```{r read_data}
load(paste0(dir_prefix,"pass_2/merged_E1_liver_singlets_merged_processed_bsAMSd.RData"))
```

```{r annotate}
annos <- c("junk",#0
           "B",#1
           "T",#2
           "NK",#3
           "B",#4
           "T",#5 Proliferating
           "Macrophage",#6
           "DC",#7
           "Macrophage",#8
           "pDC",#9
           "Neutrophil",#10
           "NK",#11
           "B",#12
           "B",#13
           "Neutrophil",#14
           "Macrophage",#15
           "Macrophage",#16 non-inflammatory
           "gdT",#17
           "Macrophage",#18 CD163
           "B",#19
           "DC",#20
           "HSC",#21
           "Mast Cell",#22
           "stroma"#23 maybe hepatocytes
           )

merged_data$anno_res0.8 <- as.character(merged_data$louvain_res0.8)
for(i in 0:23){
  merged_data@meta.data[merged_data$louvain_res0.8 == i, 'anno_res0.8'] <- annos[i+1]
}
merged_data$anno_res0.8 <- as.factor(merged_data$anno_res0.8)
```

```{r split_myelo_lympho}
lymphoid <- c("B", "T", "NK", "gdT")
myeloid <- c("DC", "pDC", "Macrophage", "Mast Cell", "Neutrophil")
merged_lympho <- subset(merged_data, subset=anno_res0.8 %in% lymphoid)
merged_myelo <- subset(merged_data, subset=anno_res0.8 %in% myeloid)

merged_lympho@meta.data <- merged_lympho@meta.data[,!grepl(colnames(merged_lympho@meta.data), pattern="^(m|louvain|RNA|seurat)")]
colnames(merged_lympho@meta.data) <- c(head(colnames(merged_lympho@meta.data), -1), "full_merged_0.8_anno")

merged_myelo@meta.data <- merged_myelo@meta.data[,!grepl(colnames(merged_myelo@meta.data), pattern="^(m|louvain|RNA|seurat)")]
colnames(merged_myelo@meta.data) <- c(head(colnames(merged_myelo@meta.data), -1), "full_merged_0.8_anno")

save(merged_lympho, file=paste0(dir_prefix,"lymphoid/merged_E1_liver_singlets_merged_processed_bsAMSd_lymphoid.RData"))

save(merged_myelo, file=paste0(dir_prefix,"myeloid/merged_E1_liver_singlets_merged_processed_bsAMSd_myeloid.RData"))
```

```{r load_myelo_lympho}
load(paste0(dir_prefix,"lymphoid/merged_E1_liver_singlets_merged_processed_bsAMSd_lymphoid.RData"))

load(paste0(dir_prefix,"myeloid/merged_E1_liver_singlets_merged_processed_bsAMSd_myeloid.RData"))
```

```{r recluster_lympho}
recluster <- function(data){
  data <- RunPCA(data, verbose=TRUE)
  data <- RunHarmony(data,
                     "LIBRARY",
                      assay.use='RNA',
                      plot_convergence = TRUE,
                      max.iter.harmony=20,
                      max.iter.cluster=30)
  data <- RunUMAP(data,
                  dims = 1:30,  # Num PCs to use
                  reduction='harmony',
                  n.neighbors = 30,  # Default. Controls how UMAP balances local (low) versus global (large) structure in the data
                  min.dist = 0.3,   # Default. Controls the size of the clusters. Should be smaller than spread
                  spread = 1,  # Default. Controls the inter-cluster distances to some extent. Should be larger than min_dist
                  a = NULL,  # Default. Can be used with b instead of using min.dist/spread
                  b = NULL,  # Default. Can be used with a instead of using min.dist/spread
                  verbose = TRUE)
  
  data <- FindNeighbors(data,
                          dims = 1:30,  # Num PCs to use
                          reduction='harmony',
                          k.param = 20,  # k for the knn algorithm
                          verbose = TRUE)
  
  for (res in c(0.2, 0.4, 0.6, 0.8, 1.0)){
    if (paste0('louvain_res', res) %in% colnames(data@meta.data)){
      data@meta.data[[paste0('louvain_res', res)]] <- NULL
    }
    data <- FindClusters(data, verbose = TRUE,
                               algorithm = 1,
                                resolution = res)
    data@meta.data[[paste0('louvain_res', res)]] <- data@meta.data$seurat_clusters
  }
  
  return(data)
}

merged_lympho <- recluster(merged_lympho)
merged_myelo <- recluster(merged_myelo)
```

```{r save_by_compartment}
save(merged_lympho, file=paste0(dir_prefix,"lymphoid/merged_E1_liver_singlets_merged_processed_bsAMSd_lymphoid.RData"))

save(merged_myelo, file=paste0(dir_prefix,"myeloid/merged_E1_liver_singlets_merged_processed_bsAMSd_myeloid.RData"))
```

```{r load_by_compartment}
load(paste0(dir_prefix,"lymphoid/merged_E1_liver_singlets_merged_processed_bsAMSd_lymphoid.RData"))

load(paste0(dir_prefix,"myeloid/merged_E1_liver_singlets_merged_processed_bsAMSd_myeloid.RData"))
```

```{r UMAPS_by_compartment}
png(filename=paste0(dir_prefix, 'lymphoid/louvain_res_1.png'), width = 5, height = 5, units = "in", res = 300)
dittoDimPlot(merged_lympho, var='louvain_res1', do.label = TRUE)
dev.off()

png(filename=paste0(dir_prefix, 'myeloid/louvain_res_1.png'), width = 5, height = 5, units = "in", res = 300)
dittoDimPlot(merged_myelo, var='louvain_res1', do.label = TRUE)
dev.off()
```

```{r markers_by_compartment}
Idents(merged_lympho) <- merged_lympho$louvain_res1
Idents(merged_myelo) <- merged_myelo$louvain_res1

lympho_markers <- FindAllMarkers(merged_lympho,
                                 assay="RNA")
lympho_markers <- lympho_markers %>% filter(p_val_adj < 0.05)
write.table(lympho_markers, file=paste0(dir_prefix, "lymphoid/res1_markers.tsv"), sep="\t")
lympho_markers_up <- lympho_markers %>% filter(avg_log2FC > 0)
lympho_markers_down <- lympho_markers %>% filter(avg_log2FC < 0)
write.table(lympho_markers_up, file=paste0(dir_prefix, "lymphoid/res1_markers_up.tsv"), sep="\t")
write.table(lympho_markers_down, file=paste0(dir_prefix, "lymphoid/res1_markers_down.tsv"), sep="\t")

myelo_markers <-  FindAllMarkers(merged_myelo,
                                 assay="RNA")
myelo_markers <- myelo_markers %>% filter(p_val_adj < 0.05)
write.table(myelo_markers, file=paste0(dir_prefix, "myeloid/res1_markers.tsv"), sep="\t")
myelo_markers_up <- myelo_markers %>% filter(avg_log2FC > 0)
myelo_markers_down <- myelo_markers %>% filter(avg_log2FC < 0)
write.table(myelo_markers_up, file=paste0(dir_prefix, "myeloid/res1_markers_up.tsv"), sep="\t")
write.table(myelo_markers_down, file=paste0(dir_prefix, "myeloid/res1_markers_down.tsv"), sep="\t")
```
I am going to use Arjun's scoring of clusters using Zilionis et. al. 2019 to help me annotate the myeloid clusters. Zilionis has a few characterizations of lymphoid cell types, but it is primarily focused on myeloid cell types.
```{r zilionis}
source('../E1_scripts/zilionis_sigs.R')
source('../E1_scripts/saturate.R')
source('../aarao_scripts/R/BootstrappedAddModuleScore.R')
for (sig in names(zilionis_mouse_sigs)) {
  nb = 30
  while (TRUE) {
    try(merged_myelo <- BootstrappedAddModuleScore(merged_myelo,
                                                  assay='RNA',
                                                  features=list(zilionis_mouse_sigs[[sig]]),
                                                  name=sig,
                                                  nbin = nb,
                                                  num_iters=100))
    if (paste0(sig, '1') %in% colnames(merged_myelo@meta.data)) {
      merged_myelo@meta.data[sig] <- merged_myelo@meta.data[paste0(sig, '1')]
      merged_myelo@meta.data[paste0(sig, '1')] <- NULL
      merged_myelo@meta.data[paste0(sig, '_75sat')] <- saturate(merged_myelo@meta.data[[sig]], sat=0.75, binary=T)
      merged_myelo@meta.data[paste0(sig, '_95sat')] <- saturate(merged_myelo@meta.data[[sig]], sat=0.95, binary=T)
      break
    } else if (nb == 5) {
      stop()
    } else {
      nb <- nb - 1
    }
  }
}

myelo_zili_95 <- colnames(merged_myelo@meta.data)[grepl(colnames(merged_myelo@meta.data), pattern = "_95sat$")]
myelo_zili_75 <- colnames(merged_myelo@meta.data)[grepl(colnames(merged_myelo@meta.data), pattern = "_75sat$")]
myelo_zili <- colnames(merged_myelo@meta.data)[(grepl(colnames(merged_myelo@meta.data), pattern = "^m")) & (!grepl(colnames(merged_myelo@meta.data), pattern = "_"))]

png(filename=paste0(dir_prefix, 'myeloid/zilionis_dotplot_sat95_myeloid.png'), width = 10, height = 5, units = "in", res = 300)
DotPlot(merged_myelo, features=myelo_zili_95, group.by='louvain_res1')+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=10))
dev.off()

png(filename=paste0(dir_prefix, 'myeloid/zilionis_dotplot_sat75_myeloid.png'), width = 10, height = 5, units = "in", res = 300)
DotPlot(merged_myelo, features=myelo_zili_75, group.by='louvain_res1')+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=10))
dev.off()

png(filename=paste0(dir_prefix, 'myeloid/zilionis_dotplot_myeloid.png'), width = 10, height = 5, units = "in", res = 300)
DotPlot(merged_myelo, features=myelo_zili, group.by='louvain_res1')+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=10))
dev.off()

save(merged_myelo, file=paste0(dir_prefix,"myeloid/merged_E1_liver_singlets_merged_processed_bsAMSd_myeloid.RData"))
```

```{r annos_by_compartment}
lympho_annos <- c("junk",#0
           "NK cell",#1 kinda weird tho
           "Plasma cell",#2 kinda weird
           "CD8 T cell",#3 
           "B cell",#4 Lots of Ribosomal also maybe a PC
           "Proliferating CD8 T cell",#5 these cells are more in G2M and S phase than the rest
                          #cell type maybe T8, higher CD28, CD8a, CD3e/d and others
           "CD4 T cell",#6 very high CD40L
           "ILC3",#7 probably 3 b/c Xcl1,Gzmc ;maybe some 2's
           "Naive B cell",#8 high IgD
           "NKT cell",#9 could also be Effector CD8 T
           "IgA Plasma cell",#10
           "gdT cell",#11
           "ILC1",#12 probably 1 because of IFNg
           "Treg",#13
           "junk"#14 Neutrophils or Macrophages maybe
)

merged_lympho$anno_lympho_res1 <- as.character(merged_lympho$louvain_res1)
for(i in c(7,12)){
  merged_lympho@meta.data[merged_lympho$louvain_res1 == i,'anno_lympho_res1'] <- lympho_annos[i+1]
}
merged_lympho$anno_lympho_res1 <- as.factor(merged_lympho$anno_lympho_res1)

merged_lympho <- subset(merged_lympho, subset=anno_lympho_res1!='junk')
merged_lympho$anno_lympho_res1 <- droplevels(merged_lympho$anno_lympho_res1)

Idents(merged_lympho) <- merged_lympho$anno_lympho_res1

myelo_annos <- c("Inflammatory Kuppfer Cell",#0 F480, C1qa, C1qb
           "Neutrophil",#1 IRF7
           "Neutrophil",#2 high mt, junk/Neut
           "Inflammatory Macrophage",#3
           "DC",#4
           "pDC",#5 pDC
           "cDC1",#6 DC1, maybe migratory
           "pDC",#7 pDC
           "Macrophage 4",#8 Mac4
           "Neutrophil",#9 Neutrophil (maybe Mono3)
           "Endothelial",#10 
           "Non-inflammatory Kuppfer Cell",#11 MoMacDC/Mac/maybe DC, has F480, Irf7, Clec4f, CD163
           "DC3",#12 DC3
           "Monocyte",#13 Mono2
           "junk",#14 
           "pre-BMP",#15 Basophil, high Gata2 and IL6, progenitor of Basophils and Mast Cells?
           "Neutrophil",#16 Neutrophil/Mono3
           "junk"#17
)

merged_myelo$anno_myelo_res1 <- as.character(merged_myelo$louvain_res1)
for(i in 0:17){
  merged_myelo@meta.data[merged_myelo$louvain_res1 == i,'anno_myelo_res1'] <- myelo_annos[i+1]
}
merged_myelo$anno_myelo_res1 <- as.factor(merged_myelo$anno_myelo_res1)

merged_myelo <- subset(merged_myelo, subset=anno_myelo_res1!='junk')
merged_myelo$anno_myelo_res1 <- droplevels(merged_myelo$anno_myelo_res1)

Idents(merged_myelo) <- merged_myelo$anno_myelo_res1
```


```{r old_annos}
png(filename=paste0(dir_prefix, 'lymphoid/old_annos_by_cluster.png'), width = 5, height = 5, units = "in", res = 300)
dittoDimPlot(merged_lympho, var='full_merged_0.8_anno', split.by='ident')
dev.off()

png(filename=paste0(dir_prefix, 'myeloid/old_annos_by_cluster.png'), width = 5, height = 5, units = "in", res = 300)
dittoDimPlot(merged_myelo, var='full_merged_0.8_anno', split.by='louvain_res0.8')
dev.off()
```

```{r save_new}
save(merged_lympho, file=paste0(dir_prefix, "lymphoid/merged_E1_liver_lymphoid_singlets_reannotated.RData"))
save(merged_myelo, file=paste0(dir_prefix, "myeloid/merged_E1_liver_myeloid_singlets_reannotated.RData"))
```

```{r new_annos}
png(filename=paste0(dir_prefix, 'lymphoid/new_annos_UMAP_lymphoid.png'), width = 7.5, height = 5, units = "in", res = 300)
dittoDimPlot(merged_lympho, var='ident', do.label = TRUE)
dev.off()

png(filename=paste0(dir_prefix, 'myeloid/new_annos_UMAP_myeloid.png'), width = 7.5, height = 5, units = "in", res = 300)
dittoDimPlot(merged_myelo, var='ident', do.label = FALSE)
dev.off()
```

```{r playground}
dittoDimPlot(merged_myelo, var='ident', do.label=FALSE)
```

```{r ages}
age_count_lympho <- as.vector(merged_lympho@meta.data %>% select(age) %>% table())
freq_by_age_lympho <- merged_lympho@meta.data %>% select(age, anno_lympho_res1) %>% group_by(age) %>% table()/age_count_lympho

freq_by_age_lympho <- t(freq_by_age_lympho)
write.table(freq_by_age_lympho, file=paste0(dir_prefix, "lymphoid/cell_type_freq_by_age.csv"), sep=',')

age_count_myelo <- as.vector(merged_myelo@meta.data %>% select(age) %>% table())
freq_by_age_myelo <- merged_myelo@meta.data %>% select(age, anno_myelo_res1) %>% group_by(age) %>% table()/age_count_myelo

freq_by_age_myelo <- t(freq_by_age_myelo)
write.table(freq_by_age_myelo, file=paste0(dir_prefix, "myeloid/cell_type_freq_by_age.csv"), sep=',')
```